ONSAS/ONSAS

ONSAS.m
examples/example02_staticVonMisesTruss_test.m
sources/outputReport.m
sources/printSolverOutput.m

solved header in increments table // change in command message

---

README.md
examples/onsasExample_simplePendulum.m
examples/onsasExample_windTurbine.m
sources/assembler.m
sources/inputVarsVerification.m
sources/stabilityAnalysis.m
sources/storeAndPlotResults.m
sources/timeStepIteration.m

bug and error fixes , changes in readme

---

ONSAS.m
examples/onsasExample_rightAngleCantileverBeam.m
examples/onsasExample_staticVonMisesTruss_test.m
examples/onsasExample_uniaxialExtension_test.m
examples/onsasExample_uniformCurvatureCantilever_test.m
examples/runTestProblems.m
examples/vonMises.dxf
examples/vonMises_noEmpyLines.dxf
runTests.sh
sources/assembler.m
sources/dxfReader.m
sources/elementBeamForces.m
sources/elementTrussInternForce.m
sources/inputVarsVerification.m
sources/isThisOctave.m
sources/meshFileReader.m
sources/stabilityAnalysis.m
sources/storeAndPlotResults.m
sources/vtkGeometry.m

Actualizate branch to add slelfWheight boolean

Actualizate branch to add slelfWheight boolean

---

examples/onsasExample_staticVonMisesTruss_test.m
sources/analyticSolVerif.m
sources/computeDeltaU.m
sources/computeMatrix.m
sources/computeRHS.m
sources/elementTrussInternForce.m
sources/extractMethodParams.m
sources/inputVarsVerification.m

linear truss elements added

---

examples/onsasExample_rightAngleCantileverBeam.m
examples/onsasExample_simplePendulumBoolean.m
sources/conversionLoadsSprings.m
sources/inputVarsVerification.m

Mauricio133

---

examples/onsasExample_rightAngleCantileverBeam.m
sources/vtkGeometry.m

change in the equivalent section in vtk geometry

---

examples/onsasExample_uniformCurvatureCantilever_test.m
sources/elementBeamForces.m

Tested using uniformCurvatureCantilever example

Updated elementBeamForces to elemen type

---

.travis.yml

test in .travis.yml

---

ONSAS.m
examples/onsasExample_uniaxialExtension_test.m
sources/inputVarsVerification.m
sources/storeAndPlotResults.m
sources/timeStepIteration.m

initial guess option

---

examples/onsasExample_1DHeatTransfer.m
examples/onsasExample_uniaxialExtension_test.m
sources/msh4Reader.m

Update branch mvanzulli/160 to solve #160

Update branch to fix sotoreAndPlotResults script

---

sources/computeFext.m

nextLoadFactor was not defiend and has been modifyed by currLoadFactor

Modifyed computeFext script

---

examples/scriptConvertExamples_jorgepz.m
examples/uniformCurvatureCantilever/onsasExample_uniformCurvatureCantilever_test.m
src/ONSAS.m
src/assembler.m
src/computeRHS.m
src/elementBeamForces.m
src/m2md.m
src/timeStepIteration.m
src/uni.md

uniformCurvatureCantilever update to new format ONSAS

uniformCurvatureCantilever update

---

.github/workflows/tests.yml
examples/staticVonMisesTruss/onsasExample_staticVonMisesTruss.m
src/ONSAS_init.m
src/ONSAS_solve.m
src/boundaryCondsProcessing.m
src/computeDeltaU.m
src/computeFext.m
src/computeRHS.m
src/printSolverOutput.m
src/timeStepIteration.m
src/vtk/vtkMainWriter.m

varios arreglos

---

.github/workflows/tests.yml
examples/nonlinearPendulum/onsasExample_nonlinearPendulum.m
test/runTestProblems_local.m
test/runTestProblems_moxunit_disp.m

added HHT validation to non linear pendulum example

---

.github/workflows/tests.yml
examples/dynamicVonMises/centralDiffDynVonMises.m
examples/dynamicVonMises/onsasExample_dynamicVonMises.m
examples/springMass/myLoadSpringMass.m
examples/springMass/onsasExample_springMass.m
src/assembler.m
test/runTestProblems_moxunit_disp.m

agrego ejemplos von mises y springmass

---

examples/nonlinearPendulum/onsasExample_nonlinearPendulum.m

added frame conssitent validation to onsasExample_nonLinPendulum

---

examples/rightAngleCantileverBeam/onsasExample_rightAngleCantilever.m
src/elements/elementBeamForces.m

New branch with cantileve beam example validation, this closes #304

added example to new branch

---

examples/rightAngleCantileverBeam/onsasExample_rightAngleCantilever.m

Update rightAngle parameters according to Le,Battini 2014

---

examples/nonlinearPendulum/onsasExample_nonlinearPendulum.m
src/ONSAS_init.m
src/assembler.m
src/boundaryCondsProcessing.m
src/elements/elementBeamForces.m
src/setDefaults.m

This feature was tested considering 2 type of  material and 2 type of elements in uniformCurvatureCantilever and added to nonLinearPendlum test.

added Boolean Self Weight considering different element and material types 

---

examples/beamTrussPendulum/onsasExample_beamTrussPendulum.m

This example aims to capture the dynamic between truss and beam element interacction. Nowdays is executed only with truss nodal gravity forces and conssitent mass matrix. Results are:
Uz end frame node:
Uz end turss node:

include multiple elements and two types of materials

---

examples/uniaxialExtension/onsasExample_uniaxialExtension.m
src/assembler.m
src/beamParameters.m
src/linearStiffMatBeam3D.m

closes #340. Results are validated using linearStaticAeroForce script  with linear beam forces

added beamParemeters function and fix run test problems into aeroForce branch

---

examples/staticVonMisesTruss/onsasExample_staticVonMisesTruss.m
src/vtk/trussVtkData.m
src/vtk/vtkBeam2SolidConverter.m
src/vtk/vtkDataConversion.m

fix bug truss vtk

---

src/computeMatrix.m

Revert "Mvanzulli/350"

---

src/aeroForce.m

added acos control in aeroForce function

---

src/assembler.m
src/computeMatrix.m

Naming different time variable in assembler

---

docs/src/howtouse/creatingModels.md

fix docs nodaldispdamping

---

docs/src/howtouse/creatingModels.md

fix params arc length

---

.github/workflows/tests.yml
examples/simpleWindTurbine/onsasExample_simpleWindTurbine.m
examples/simpleWindTurbine/windVel.m
test/runTestProblems_local.m
test/runTestProblems_moxunit_disp.m

This PR close Issue #406
The example execution time is 40s in my PC.

Add wind turbine test

---

src/elements/elementBeamForces.m
src/elements/linearStiffMatBeam3D.m

deleted rotation matrix

---

examples/springMass/springMass.m
src/vtk/vtkDataConversion.m

fix bug in vtkData for node type

---

examples/beamTrussPendulum/onsasExample_beamTrussPendulum.m
examples/dynamicVonMises/onsasExample_dynamicVonMises.m
examples/frameLinearAnalysis/onsasExample_frameLinearAnalysis.m
examples/roordaFrame/onsasExample_RoordaFrame.m
src/elements/elementBeamForces.m

and other small changes in other examples
closes #326

fix roorda frame example

---

.github/workflows/tests.yml
docs/src/howtouse/creatingModels.md
examples/frameLinearAnalysis/frameLinearAnalysis.m
src/crossSectionProps.m
test/runTestProblems_local.m
test/runTestProblems_moxunit_disp.m

fix error in Izz inertia + add torsion validation test

---

docs/src/howtouse/creatingModels.md
examples/beamTrussPendulum/onsasExample_beamTrussPendulum.m
examples/dynamicVonMises/onsasExample_dynamicVonMises.m
examples/eulerColumn/onsasExample_eulerColumn.m
examples/frameLinearAnalysis/frameLinearAnalysis.m
examples/nonLinearCantileverAero/nonLinearCantileverAero.m
examples/nonlinearPendulum/onsasExample_nonlinearPendulum.m
examples/rightAngleCantileverBeam/onsasExample_rightAngleCantilever.m
examples/simpleWindTurbine/onsasExample_simpleWindTurbine.m
examples/springMass/springMass.m
examples/staticVonMisesTruss/onsasExample_staticVonMisesTruss.m
examples/uniformCurvatureCantilever/onsasExample_uniformCurvatureCantilever.m
src/assembler.m
src/elements/elementBeamForces.m
src/elements/elementTrussMassForce.m
src/elements/linearStiffMatBeam3D.m
src/initialCondsProcessing.m
src/setDefaults.m
src/tangentInertialMassMatrix.m

implemented idiomatic cross section

---

docs/make.jl

I am removing this example from the docs since it takes too much time to solve in ONSAS.m and the doc page is not yet complete.

remove inclusion example from docs

---

src/elements/frame/hydroFrameForces.m

fixed boolean-branches x in hydroFrame script

---

src/elements/frame/hydroFrameForces.m

Implemented uniform velocity boolean. This is related with #468

implemented into `hydroFrameForces.m` uniform velocity boolean

---

src/ONSAS.m
src/core/ONSAS_solve.m
src/elements/frame/frame_internal_force.m
src/outputReport.m

closes #543  . decided to leave just a percentage progress bar.

add progress bar

---

src/elements/frame/frame_fluid_force.m

Fixing non-linear aerodynamics example

---

docs/src/howtouse/creatingModels.md
examples/nonlinearPendulum/nonlinearPendulum.m
src/core/assembler.m
src/core/boundaryCondsProcessing.m
src/setDefaults.m
src/vtk/vtkMainWriter.m

closes #535  and solves first sub-task of issue #535

add spring feature and fix vtk index issue

---

src/elements/frame/frame_inertial_force.m

Correcting a mistake regarding massratio for added mass

 Correcting added mass

---

docs/src/index.md

This PR close a sub-task of #497 :blue_book:

fixing ring gif

---

src/crossSectionProps.m

hollow pipe crosse section
I quickly found the formulas here (not a very reliable source but did not feel the need to double check those intuitives formulas) https://www.calcresource.com/cross-section-ctube.html

Adding a pipe cross section

---

.github/workflows/matlab_tests_and_docs.yml
test/runTestProblems_local.m

this PR adds test time reporting to help on the issue #580

update matlab action and add time to tests

---

examples/addedMass pendulum/ONSAS_AMValidation.m

Removing functions in the end for Octave use

Added mass example corrections for Octave

---

src/elements/frame/WOMV4.m

Comments to have rights q0 for Ex 2 Ex 3 validation

Comments on WOMV4.m

---

examples/uniaxialCompression/uniaxialCompression.m

Validation plot uniaxial compression example (#599)

---

test/runTestProblems_moxunit_disp.m

add more tests to the CI while keeping code coverage working. Related to #432

add some tests

---

examples/simplePropeller/simplePropeller.m
examples/staticVonMisesTruss/staticVonMisesTruss.m
examples/uniaxialCompression/uniaxialCompression.m
examples/uniformCurvatureCantilever/uniformCurvatureCantilever.m
test/gaussIntegrationTest.m
test/runTestProblems_moxunit_disp.m

fixed the code coverage when running more than one test. thanks to @joergbrech !

adding tests to coverage

---

.github/workflows/octave_docker_tests.yml

fix octave_tests workflow

---

src/elements/frame/integFluidForce.m

Correcting my error

---

examples/ringPlaneStrain/ringPlaneStrain.m

Ring plane strain docs

---

README.md
docs/src/index.md

still pending remove from header. related to #669

remove @mforets as author as he requested

---

docs/src/index.md

I misunderstood the request by @mforets regarding https://github.com/ONSAS/ONSAS/pull/673 . He said he would not be included as co-author in a potential publication (not in the code), so I am restating him as co-author of the code. Thanks for the clarification!

clarification authorship code

---

docs/src/creatingModels.md
examples/staticVonMisesTruss/staticVonMisesTruss.m

add vector archlength step to docs

---

docs/src/creatingModels.md
examples/staticVonMisesTruss/staticVonMisesTruss.m
src/core/computeDeltaU.m
src/utils/setDefaults.m

add jirasek variant to docs

---

examples/cantileverPlate/cantileverPlate.m
src/core/ONSAS_init.m
src/elements/triangle/internal_forces_plate_triangle.m

add computation of internal forces for plate element. related to #558

add moments to plate element function

---

CITATION.cff
DESCRIPTION
docs/src/index.md
src/interface/ONSAS_init.m

ongoing revisions of code and docs...

Version and description updates

---

src/core/boundaryCondsProcessing.m
src/crossSections/innerDragCoefCircular.m
src/elements/frame/frame_fluid_force.m
src/elements/frame/integFluidForce.m
src/materials/cosseratNHC.m
src/mesh/elem2NodalLoads.m
src/utils/plotForcesNorms.m
src/utils/printSolverOutput.m
test/gaussIntegrationTest.m
test/runTestProblems_local.m

Fix minor typos in test and src folders

---

.github/workflows/clean-gh-pages.yml
.github/workflows/matlab_tests_and_docs.yml
docs/Project.toml
docs/make.jl

Add Documenter.jl to docs deps

---

docs/src/creatingModels.md

Fix docs inconsistencies 

---

src/elements/triangle/_internal_forces_shell_triangle.m
src/elements/triangle/internal_forces_shell_triangle.m

@schaedleralmeida : I am opening the PR so that we can see the changes you are proposing as you/we work on them.

changes shell element

---

src/vtk/shellVtkData.m

closes https://github.com/ONSAS/ONSAS/issues/776

fix deformation of shell and plate vtks
